import { sanitizeFilename } from './sanitize'
import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import type { IngestedFile } from '../hooks/useFileIngestion'

export async function generateZip(
  files: IngestedFile[],
  productName: string,
  metadata?: string,
  onProgress?: (percent: number) => void
): Promise<void> {
  const zip = new JSZip()

  const sourceFolder  = zip.folder('Source_Files')!
  const previewFolder = zip.folder('Preview')!
  const metaFolder    = zip.folder('Metadata')!

  for (const ingestedFile of files) {
    const { file } = ingestedFile
    const data = await readFileAsArrayBuffer(file)
    if (file.type.startsWith('image/')) {
      previewFolder.file(file.name, data)
    } else {
      sourceFolder.file(sanitizeFilename(file.name), data)
    }
  }

  // Add SEO metadata if provided
  if (metadata) {
    metaFolder.file('listing-description.md', metadata)
  }

  const readmeContent = `# ${productName || 'Digital Asset Package'}

Generated by AssetForge Labs
Date: ${new Date().toLocaleDateString()}

## Folder Structure
- /Source_Files → Your main asset files
- /Preview      → Preview images
- /Metadata     → SEO listing description

## License
Personal and commercial use allowed.
`
  metaFolder.file('README.md', readmeContent)

  const blob = await zip.generateAsync(
    { type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } },
    (meta) => { if (onProgress) onProgress(Math.round(meta.percent)) }
  )

  saveAs(blob, `${(productName || 'AssetForgeLabs-Package').replace(/\s+/g, '_')}.zip`)
}

function readFileAsArrayBuffer(file: File): Promise<ArrayBuffer> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload  = () => resolve(reader.result as ArrayBuffer)
    reader.onerror = () => reject(new Error('Failed to read file'))
    reader.readAsArrayBuffer(file)
  })
}