import { sanitizeFilename } from './sanitize'
import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import type { IngestedFile } from '../hooks/useFileIngestion'

export async function generateZip(
  files: IngestedFile[],
  productName: string,
  metadata?: string,
  onProgress?: (percent: number) => void
): Promise<void> {
  const zip = new JSZip()

  // 1. Create the internal folder structure
  const sourceFolder  = zip.folder('Source_Files')!
  const previewFolder = zip.folder('Preview')!
  const metaFolder    = zip.folder('Metadata')!

  // 2. Distribute the ingested files
  for (const ingestedFile of files) {
    const { file } = ingestedFile
    const data = await readFileAsArrayBuffer(file)
    if (file.type.startsWith('image/')) {
      previewFolder.file(file.name, data)
    } else {
      sourceFolder.file(sanitizeFilename(file.name), data)
    }
  }

  // 3. Add SEO metadata to the Metadata folder if provided
  if (metadata) {
    metaFolder.file('listing-description.md', metadata)
  }

  // 4. Standard technical README for the Metadata folder
  const readmeContent = `# ${productName || 'Digital Asset Package'}

Generated by AssetForge Labs — https://assetforgelabs.com
Date: ${new Date().toLocaleDateString()}

## Folder Structure
- /Source_Files → Your main asset files
- /Preview      → Preview images
- /Metadata     → SEO listing description

## License
Personal and commercial use allowed.
`
  metaFolder.file('README.md', readmeContent)

  // ====================================================================
  // 🚀 STEP 2: THE AUTOMATED VIRAL LOOP ENGINE
  // This drops directly into the ROOT of the ZIP file so buyers see it immediately
  // ====================================================================
  const viralLoopContent = `==================================================
📦 DELIVERED SECURELY VIA ASSETFORGE LABS
==================================================

Thank you for downloading this digital product! Your files have been 
securely compiled, structured, and compressed for clean extraction.

Are you a digital product creator yourself? 
Stop manually zipping files and guessing SEO metadata tags.

Build your marketplace packages in under 60 seconds with AssetForge:
👉 100% Client-Side Processing (Your files never touch a server)
👉 Instant Listing Preview Visualizers
👉 Auto-Generated High-Ranking SEO Metadata

Launch the free browser tool today:
✨ https://assetforgelabs.com

==================================================`;

  zip.file("PACKAGED_BY_ASSETFORGE.txt", viralLoopContent);
  // ====================================================================

  // 5. Generate and download the final ZIP Blob
  const blob = await zip.generateAsync(
    { type: 'blob', compression: 'DEFLATE', compressionOptions: { level: 6 } },
    (meta) => { if (onProgress) onProgress(Math.round(meta.percent)) }
  )

  saveAs(blob, `${(productName || 'AssetForgeLabs-Package').replace(/\s+/g, '_')}.zip`)
}

function readFileAsArrayBuffer(file: File): Promise<ArrayBuffer> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload  = () => resolve(reader.result as ArrayBuffer)
    reader.onerror = () => reject(new Error('Failed to read file'))
    reader.readAsArrayBuffer(file)
  })
}
